### ISSUE TITLE
Can't fetch "plusoners", "resharers" on post

### ISSUE THREAD

**Issue by igrigorik** [nfm/gplus#5]
An activity carries the count for comments, pluses and reshares, but all of those also provide a URI to fetch the actual comments or reshares. The gem currently provides a way to fetch comments, but nothing for plusoners / resharers -- would be great to have!

**Comment by nfm** [comment]
Thanks for the feedback, @igrigorik.

I've just released version `2.1.0`, which adds this feature. The README gives an example of how to use `list_people_by_activity`. Check out the official API documentation too: https://developers.google.com/+/api/latest/people/listByActivity.

**Comment by igrigorik** [comment]
Nicholas, that was fast! Great stuff, thanks! :)
